---

- name: Install Ingress mandatory
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml
  tags:
  - install_ingress

- name: Copy ingress-svc file
  template:
    src: ingress-svc.j2
    dest: /tmp/ingress-svc.yaml
  tags:
  - install_ingress

- name: Install Ingress service
  shell: kubectl apply -f /tmp/ingress-svc.yaml
  tags:
  - install_ingress
