---

- name: Kubeadm init
  shell: kubeadm init --apiserver-advertise-address={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} --pod-network-cidr={{ network }}
  ignore_errors: yes
  tags:
  - kubeadm_init

- name: Export KUBECONFIG
  lineinfile: 
    path: ~/.bashrc
    line: 'export KUBECONFIG=/etc/kubernetes/admin.conf'
    insertafter: 'EOF'
    state: present
  tags:
  - kubeadm_init

#- name: Kubectl apply flannel
#  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
# tags:
# - kubeadm_init

- name: Copy Calico file
  copy:
    src: files/calico.yaml
    dest: /tmp/calico.yaml
  tags:
 - kubeadm_init

- name: Kubectl apply Calico
  shell: kubectl apply -f /tmp/calico.yaml
 tags:
 - kubeadm_init


- name: Create join token
  shell: kubeadm token create --print-join-command
  register: K8S_JOIN 
  tags:
  - kube_joinnode

- name: Join nodes
  shell: "{{ K8S_JOIN.stdout }}"
  delegate_to: "{{item}}"
  delegate_facts: True
  loop: "{{groups['kubernodes']}}"
  ignore_errors: yes
  tags:
  - kube_joinnode

- name: Set label for agents
  shell: kubectl label --overwrite nodes "{{item}}" node-role.kubernetes.io/agent=agent
  with_items: "{{groups['kuberagents']}}"
  tags:
  - set_lable

- name: Set label for worker
  shell: kubectl label --overwrite nodes "{{item}}" node-role.kubernetes.io/worker=worker
  with_items: "{{groups['kuberworkers']}}"
  tags:
  - set_lable
